###

GET http://localhost:3000/

###

GET http://localhost:3000/abc

###

GET http://localhost:3000/api/v1/categories

###

GET http://localhost:3000/api/v1/posts

###

GET http://localhost:3000/api/v1/posts/1

###

POST http://localhost:3000/api/v1/posts
Content-Type: application/json

{
  "title": "post_title",
  "content": "post_content",
  "category": {
    "id": 1,
    "name": "category1",
    "posts": []
  }
}

###

PUT http://localhost:3000/api/v1/posts
Content-Type: application/json

[
  {
    "title": "post_title1",
    "content": "post_content1",
    "category": {
      "id": 1,
      "name": "category1",
      "posts": []
    }
  },
  {
    "title": "post_title2",
    "content": "post_content2",
    "category": {
      "id": 1,
      "name": "category1",
      "posts": []
    }
  }
]

###

PATCH http://localhost:3000/api/v1/posts/1
Content-Type: application/json

{
  "content": "eloelo320",
  "published": true
}

###

DELETE http://localhost:3000/api/v1/posts/2

###